<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerInxUfVR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerInxUfVR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerInxUfVR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerInxUfVR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerInxUfVR\App_KernelDevDebugContainer([
    'container.build_hash' => 'InxUfVR',
    'container.build_id' => '2c27167d',
    'container.build_time' => 1666352195,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerInxUfVR');
