<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'api_genid' => [['id'], ['_controller' => 'api_platform.action.not_exposed', '_api_respond' => 'true'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/.well-known/genid']], [], [], []],
    'api_entrypoint' => [['index', '_format'], ['_controller' => 'api_platform.action.entrypoint', '_format' => '', '_api_respond' => 'true', 'index' => 'index'], ['index' => 'index'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', 'index', 'index', true]], [], [], []],
    'api_doc' => [['_format'], ['_controller' => 'api_platform.action.documentation', '_format' => '', '_api_respond' => 'true'], [], [['variable', '.', '[^/]++', '_format', true], ['text', '/docs']], [], [], []],
    'api_jsonld_context' => [['shortName', '_format'], ['_controller' => 'api_platform.jsonld.action.context', '_format' => 'jsonld', '_api_respond' => 'true'], ['shortName' => '[^.]+', '_format' => 'jsonld'], [['variable', '.', 'jsonld', '_format', true], ['variable', '/', '[^.]+', 'shortName', true], ['text', '/contexts']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'gestion_utilisateur' => [[], ['_controller' => 'App\\Controller\\GetApiController::gestionUtilisateur'], [], [['text', '/gestion/utilisateur']], [], [], []],
    'gestion_agences' => [[], ['_controller' => 'App\\Controller\\GetApiController::gestionAgences'], [], [['text', '/gestion/agences']], [], [], []],
    'gestion_vehicules' => [[], ['_controller' => 'App\\Controller\\GetApiController::gestionVehicules'], [], [['text', '/gestion/vehicules']], [], [], []],
    'patch_disable_gestion_utilisateur' => [['userId'], ['_controller' => 'App\\Controller\\PatchApiController::patchDisableGestionUtilisateur'], [], [['variable', '/', '[^/]++', 'userId', true], ['text', '/patch/disable/gestion/utilisateur']], [], [], []],
    'patch_enable_gestion_utilisateur' => [['userId'], ['_controller' => 'App\\Controller\\PatchApiController::patchEnableGestionUtilisateur'], [], [['variable', '/', '[^/]++', 'userId', true], ['text', '/patch/enable/gestion/utilisateur']], [], [], []],
    'patch_disable_gestion_vehicules' => [['vehiculeId'], ['_controller' => 'App\\Controller\\PatchApiController::patchDisableVehicule'], [], [['variable', '/', '[^/]++', 'vehiculeId', true], ['text', '/patch/disable/gestion/vehicules']], [], [], []],
    'patch_enable_gestion_vehicules' => [['vehiculeId'], ['_controller' => 'App\\Controller\\PatchApiController::patchEnableGestionVehicule'], [], [['variable', '/', '[^/]++', 'vehiculeId', true], ['text', '/patch/enable/gestion/vehicules']], [], [], []],
    'patch_delete_gestion_utilisateur' => [['userId'], ['_controller' => 'App\\Controller\\PatchApiController::patchDeleteGestionUtilisateur'], [], [['variable', '/', '[^/]++', 'userId', true], ['text', '/delete/gestion/utilisateur']], [], [], []],
];
